import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "@/client/react-query/react-query";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "ADTO Client Side Landing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={` antialiased`}
        >
          <main>{children}</main>
          <Toaster />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
