import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "ADTO Admin Side",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div
            className={`antialiased`}
        >
            <SidebarProvider>

                <AppSidebar />
                <main>{children}</main>
            </SidebarProvider>
        </div>
    );
}
